interface=vmbr0
bind-dynamic
dhcp-authoritative
dhcp-range=10.44.0.100,10.44.0.199,255.255.255.0,12h
dhcp-option=option:router,10.44.0.1
dhcp-option=option:dns-server,10.44.0.1
domain=pve-lab.internal
local=/pve-lab.internal/
domain-needed
bogus-priv
