#!/usr/sbin/nft -f

flush ruleset

table inet pve_lab_filter {
    chain forward {
        type filter hook forward priority filter; policy drop;

        ct state established,related accept
        iifname "vmbr0" oifname != "vmbr0" accept
        iifname "vmbr0" oifname "vmbr0" accept
    }
}

table ip pve_lab_nat {
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;

        ip saddr 10.44.0.0/24 oifname != "vmbr0" masquerade
    }
}
